### ISSUE TITLE
Do you have a rough plan for open sourcing? Thank you.

### ISSUE THREAD

**Issue by sanbuphy** [SHShim0513/SD-VITON#1]

**Comment by SHShim0513** [comment]
Hi, @sanbuphy!

First, thank you for interest of our work.

We will plan to release the training, inference codes, and the checkpoints before 31, January, 2024.

Best regards,
Sang-Heon Shim

**Comment by sanbuphy** [comment]
> Hi, @sanbuphy!
> 
> First, thank you for interest of our work.
> 
> We will plan to release the training, inference codes, and the checkpoints before 31, January, 2024.
> 
> Best regards, Sang-Heon Shim

Thank you very much and happy new year.
Best wishes.

**Comment by oylz** [comment]
@sanbuphy than you, wating
